name: CI
on: push
env:
  ESLINT_USE_FLAT_CONFIG: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install ESLint
      run: |
        npm install eslint
        npm install @microsoft/eslint-formatter-sarif
    - name: Run ESLint
      run: npx eslint .
        --config .eslintrc.json
        --ext .js,.jsx,.ts,.tsx
      continue-on-error: false
